version: '3.9'

services:
  web:
    build: .
    container_name: django-fakeus
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000

  nginx:
    image: nginx:latest
    container_name: nginx-fakeus
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
