version: '3'

services:
  web:
    build: .
    container_name: fakeus_web
    command: gunicorn fakeUSGenerator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000

  nginx:
    image: nginx:latest
    container_name: fakeus_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
